name: ChatSensei

on:
  push:
    paths:
      - ChatSensei/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ChatSensei
    - name: Build
      run: dotnet build --no-restore
      working-directory: ChatSensei
    - name: Test
      env:
        openAIKey: ${{ secrets.OPENAI_TOKEN }}
      run: dotnet test --no-build --verbosity normal
      working-directory: ChatSensei
